---
name: Build an image, then push to Dockerhub.

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      ref:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: "latest"
    secrets:
      DH_USER:
        required: true
      DH_PASS:
        required: true

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sickday/${{ inputs.image }}:${{ inputs.tag }}
