---
name: Elixir with NodeJs

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]
    paths: ['elixir-node/**']

jobs:
  ElixirNodeJS:
    uses: ./.github/workflows/build_push.yml
    with:
      ref: ${{ github.ref }}
      path: elixir-node/
      file: "Dockerfile"
      image: elixir
      tag: node
    secrets:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DH_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
