---
name: SDL2

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'sdl2/**'

jobs:
  DebianSDL2:
    uses: ./.github/workflows/build_push.yml
    with:
      ref: ${{ github.ref }}
      path: sdl2/
      file: Debian.Dockerfile
      image: sdl2
      tag: latest
    secrets:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DH_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
  RubySDL2:
    uses: ./.github/workflows/build_push.yml
    with:
      ref: ${{ github.ref }}
      path: sdl2/
      file: Ruby.Dockerfile
      image: sdl2
      tag: ruby
  PythonSDL2:
    uses: ./.github/workflows/build_push.yml
    with:
      ref: ${{ github.ref }}
      path: sdl2/
      file: Python.Dockerfile
      image: sdl2
      tag: python
