on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'sdl2/**'

jobs:
  build-and-push:
    uses: ./.github/workflows/build_push.yml
    with:
      ref: ${{ github.ref }}
      image: sdl2
      tag: latest
    secrets:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DH_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
