---
name: SDL2

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'sdl2/**'

jobs:
  SDL2:
    strategy:
      matrix: 
        subtype: ["Debian", "Python", "Ruby"]
    uses: ./.github/workflows/build_push.yml
    with:
      ref: ${{ github.ref }}
      path: sdl2/
      file: "${{ matrix.subtype }}.Dockerfile"
      image: sdl2
      tag: ${{ matrix.subtype }}
    secrets:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DH_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
